name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Setup
        run: npm i -g pnpm@9

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm run lint

      - name: Typecheck devpilot plugin
        run: pnpm -C packages/devpilot-plugin-vue-scan run typecheck

      # - name: Test
      #   run: pnpm run test
